#!/bin/sh

if [[ -n `git diff --name-only --cached | grep "src/js/.*\.js$"` ]]; then
    echo "javascript updated. bumping patch version"
    grunt bump:patch
elif [[ -n `git diff --name-only --cached | grep "src/.*$"` ]]; then
    echo "non-js src updated. bumping build version"
    grunt bump:prerelease
else
    echo "non-src changes. not bumping version"
#    grunt bump:build
fi

git add package.json
